#request
uint8 payload_index 1   # see enum E_DjiMountPosition in dji_typedef.h

---
#response


bool success
# vector of image info
MediaInfo result 
# total_count from enum T_DjiCameraManagerFileList in dji_camera_manager.h
int16 count
