#request
uint8 payload_index 1       # see enum E_DjiMountPosition in dji_typedef.h
uint8 photo_aeb_count       #see enum E_DjiCameraManagerPhotoAEBCount in dji_camera_manager.h

---
#response
bool success