#request
uint8 payload_index 1       # see enum E_DjiMountPosition in dji_typedef.h
---
#response
bool success
int8 shutter_speed          # see enum E_DjiCameraManagerShutterSpeed in dji_camera_manager.h 
                            # potential inputs from 0 to 66 and 0xFF for unkown