#request
uint8 payload_index 1           # see enum E_DjiMountPosition in dji_typedef.h
uint8 num_photos_to_capture     # 0:reserve 1~254:number 255:keep capturing till stop
int16 time_interval             # time interval between two captures (second)

---
#response
bool success