#request
uint8 payload_index 1 # see enum E_DjiMountPosition in dji_typedef.h
uint8 work_mode # see E_DjiCameraManagerExposureMode in dji_camera_manager.h
uint8 ev_factor # see enum E_DjiCameraManagerExposureCompensation in dji_camera_manager.h
---
#response
bool success