#request
uint8 payload_index 1       # see enum E_DjiMountPosition in dji_typedef.h

---
#response
bool success
float64 longitude
float64 latitude
int32 altitude
int32 distance
int16 screen_x
int16 screen_y
bool enable_lidar
uint8 exception
