psdk_wrapper_node:
  ros__parameters:
    app_name: "TestPSDK"
    app_id: "127179"
    app_key: "591db151944fba0b9acab08217f2f73"
    app_license: "zldHdiIMWWdRuFKybq+gqwrnlsP7s1K2VI+9DrpZ8GMQ31w3kwJ6lfU2GUiCbhn4SlEAHqlBcgbly+gnzPwy7ymRNtqLP3L93ur6ZJh/kypMhKyAlIbzPq8lvsiBe94VrwKCuxMuyQW638fXveq+YTB9XEz5Wic0HukL8dO/Adc7AHObq5Dxo791+UaPzJbkJdKuUL1qmP/KQ4hMHnCbmtfC7Jpe4Na+CEIywOE1Yavgrel6MNfV1DnOCrS6GBAvbM/AaqnWv9Sbml5vaDWHDKMZMDhXp9F9A2zGd6k0UkHzFI9Ey4ZjCrUO/7OzecFD9ycsJCxGsTWjOyZIBAXjbw=="
    developer_account: "developer_account"
    baudrate: "921600"
    hardware_connection: "DJI_USE_UART_AND_USB_BULK_DEVICE"


