int16 current            # ESC current, unit: mA
int16 speed              # ESC speed, unit: rpm
uint16 voltage           # Input power from battery to ESC, unit: mV
int16 temperature        # ESC temperature, unit: degree C
int16 stall               # Motor is stall
int16 empty               # Motor has no load
int16 unbalanced          # Motor speed is unbalanced
int16 escDisconnected     # ESC is disconnected
int16 temperatureHigh     # Temperature is high