name: Build Documentation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x  # Change this to the Python version your Sphinx project requires

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd docs
        pip install -r requirements.txt  # Adjust this if your dependencies are in a different file

    - name: Install Doxygen 
      run: |
        wget https://www.doxygen.nl/files/doxygen-1.9.7.linux.bin.tar.gz
        tar -xzvf doxygen-1.9.7.linux.bin.tar.gz
        cd doxygen-1.9.7
        sudo make install

    - name: Build Documentation
      run: |
        make -C docs html  # This assumes your Sphinx configuration is in a 'docs' folder

    # - name: Deploy to GitHub Pages (optional)
      # Uncomment the following lines if you want to deploy to GitHub Pages
      # run: |
        # git checkout gh-pages
        # cp -r docs/_build/html/* .
        # git add .
        # git commit -m "Update documentation"
        # git push origin gh-pages
